[package]
name = "custom_source"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
libobs-simple-macro = { workspace = true }
libobs-wrapper = { workspace = true }
libobs-simple = { workspace = true }
