[package]
name = "obs-preview"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.8"
libobs-wrapper = { workspace = true }
libobs-simple = { path = "../../libobs-simple" }
winit = "0.30.12"
