[package]
name = "obs-preview"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
libobs-wrapper = { path = "../../libobs-wrapper", features = ["blocking"] }
libobs-sources = { path = "../../libobs-sources", features = ["blocking"] }
winit = "0.30.9"
