[package]
name = "encoder_switch"
version = "0.1.0"
edition = "2024"

[dependencies]
libobs-sources = { path = "../../../libobs-sources" }
libobs-wrapper = { workspace = true }
color-eyre = "0.6"
env_logger = "0.11.8"
