[test-groups]
actual-source-capture = { max-threads = 1 }

[profile.default]
retries = 2

[[profile.default.overrides]]
filter = 'binary(/^gpu_/)'
test-group = 'actual-source-capture'

[profile.ci]
# Do not cancel the test run on the first failure.
fail-fast = false
default-filter = "not binary(/^gpu_/)"