[package]
name = "monitor-capture"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libobs-wrapper = { workspace = true }
libobs-sources = { path = "../../libobs-sources" }
anyhow = "1.0.98"
